name: NestJS deployment staging

on:
  release:
    types: [ published ]

jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run gen
      - run: npm run test
      - run: npm run build

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        id: install

      - name: Install skaffold
        run: |
          sudo curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/
          sudo rm skaffold

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # if you have/need it
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Deploy
        run: |
          aws eks update-kubeconfig --name ${{ secrets.KUBECONFIG_NAME }}
          skaffold run -n ${{ secrets.SKAFFOLD_NAMESPACE }} -p dev
